//go:build ignore
// +build ignore

package main

import (
	"log"
	"os"
	"text/template"
)

func main() {

	entries, err := os.ReadDir("../aws-sdk-go-v2/service")
	if err != nil {
		log.Fatal(err)
	}

	f, err := os.Create("cmd/services.go")
	defer f.Close()

	packageTemplate.Execute(f, entries)
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.

package cmd

import (
{{- range . }}
    {{ if ne .Name "internal" }}
		"github.com/aws/aws-sdk-go-v2/service/{{ .Name }}"
	{{ end }}
{{- end }}
)

func initClients () []interface{} {
	clients := []interface{}{}
{{- range . }}
    {{ if ne .Name "internal" }}
		clients = append(clients,{{ .Name }}.Client{})
	{{ end }}
{{- end }}	
	return clients
}
`))
