// Code generated by go generate; DO NOT EDIT.

package cmd

import (
    
		"github.com/aws/aws-sdk-go-v2/service/accessanalyzer"
	
    
		"github.com/aws/aws-sdk-go-v2/service/account"
	
    
		"github.com/aws/aws-sdk-go-v2/service/acm"
	
    
		"github.com/aws/aws-sdk-go-v2/service/acmpca"
	
    
		"github.com/aws/aws-sdk-go-v2/service/alexaforbusiness"
	
    
		"github.com/aws/aws-sdk-go-v2/service/amp"
	
    
		"github.com/aws/aws-sdk-go-v2/service/amplify"
	
    
		"github.com/aws/aws-sdk-go-v2/service/amplifybackend"
	
    
		"github.com/aws/aws-sdk-go-v2/service/amplifyuibuilder"
	
    
		"github.com/aws/aws-sdk-go-v2/service/apigateway"
	
    
		"github.com/aws/aws-sdk-go-v2/service/apigatewaymanagementapi"
	
    
		"github.com/aws/aws-sdk-go-v2/service/apigatewayv2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/appconfig"
	
    
		"github.com/aws/aws-sdk-go-v2/service/appconfigdata"
	
    
		"github.com/aws/aws-sdk-go-v2/service/appfabric"
	
    
		"github.com/aws/aws-sdk-go-v2/service/appflow"
	
    
		"github.com/aws/aws-sdk-go-v2/service/appintegrations"
	
    
		"github.com/aws/aws-sdk-go-v2/service/applicationautoscaling"
	
    
		"github.com/aws/aws-sdk-go-v2/service/applicationcostprofiler"
	
    
		"github.com/aws/aws-sdk-go-v2/service/applicationdiscoveryservice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/applicationinsights"
	
    
		"github.com/aws/aws-sdk-go-v2/service/appmesh"
	
    
		"github.com/aws/aws-sdk-go-v2/service/apprunner"
	
    
		"github.com/aws/aws-sdk-go-v2/service/appstream"
	
    
		"github.com/aws/aws-sdk-go-v2/service/appsync"
	
    
		"github.com/aws/aws-sdk-go-v2/service/arczonalshift"
	
    
		"github.com/aws/aws-sdk-go-v2/service/athena"
	
    
		"github.com/aws/aws-sdk-go-v2/service/auditmanager"
	
    
		"github.com/aws/aws-sdk-go-v2/service/autoscaling"
	
    
		"github.com/aws/aws-sdk-go-v2/service/autoscalingplans"
	
    
		"github.com/aws/aws-sdk-go-v2/service/backup"
	
    
		"github.com/aws/aws-sdk-go-v2/service/backupgateway"
	
    
		"github.com/aws/aws-sdk-go-v2/service/backupstorage"
	
    
		"github.com/aws/aws-sdk-go-v2/service/batch"
	
    
		"github.com/aws/aws-sdk-go-v2/service/billingconductor"
	
    
		"github.com/aws/aws-sdk-go-v2/service/braket"
	
    
		"github.com/aws/aws-sdk-go-v2/service/budgets"
	
    
		"github.com/aws/aws-sdk-go-v2/service/chime"
	
    
		"github.com/aws/aws-sdk-go-v2/service/chimesdkidentity"
	
    
		"github.com/aws/aws-sdk-go-v2/service/chimesdkmediapipelines"
	
    
		"github.com/aws/aws-sdk-go-v2/service/chimesdkmeetings"
	
    
		"github.com/aws/aws-sdk-go-v2/service/chimesdkmessaging"
	
    
		"github.com/aws/aws-sdk-go-v2/service/chimesdkvoice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cleanrooms"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloud9"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudcontrol"
	
    
		"github.com/aws/aws-sdk-go-v2/service/clouddirectory"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudformation"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudfront"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudhsm"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudhsmv2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudsearch"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudsearchdomain"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudtrail"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudtraildata"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudwatch"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudwatchevents"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codeartifact"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codebuild"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codecatalyst"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codecommit"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codedeploy"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codeguruprofiler"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codegurureviewer"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codegurusecurity"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codepipeline"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codestar"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codestarconnections"
	
    
		"github.com/aws/aws-sdk-go-v2/service/codestarnotifications"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cognitoidentity"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider"
	
    
		"github.com/aws/aws-sdk-go-v2/service/cognitosync"
	
    
		"github.com/aws/aws-sdk-go-v2/service/comprehend"
	
    
		"github.com/aws/aws-sdk-go-v2/service/comprehendmedical"
	
    
		"github.com/aws/aws-sdk-go-v2/service/computeoptimizer"
	
    
		"github.com/aws/aws-sdk-go-v2/service/configservice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/connect"
	
    
		"github.com/aws/aws-sdk-go-v2/service/connectcampaigns"
	
    
		"github.com/aws/aws-sdk-go-v2/service/connectcases"
	
    
		"github.com/aws/aws-sdk-go-v2/service/connectcontactlens"
	
    
		"github.com/aws/aws-sdk-go-v2/service/connectparticipant"
	
    
		"github.com/aws/aws-sdk-go-v2/service/controltower"
	
    
		"github.com/aws/aws-sdk-go-v2/service/costandusagereportservice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/costexplorer"
	
    
		"github.com/aws/aws-sdk-go-v2/service/customerprofiles"
	
    
		"github.com/aws/aws-sdk-go-v2/service/databasemigrationservice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/databrew"
	
    
		"github.com/aws/aws-sdk-go-v2/service/dataexchange"
	
    
		"github.com/aws/aws-sdk-go-v2/service/datapipeline"
	
    
		"github.com/aws/aws-sdk-go-v2/service/datasync"
	
    
		"github.com/aws/aws-sdk-go-v2/service/dax"
	
    
		"github.com/aws/aws-sdk-go-v2/service/detective"
	
    
		"github.com/aws/aws-sdk-go-v2/service/devicefarm"
	
    
		"github.com/aws/aws-sdk-go-v2/service/devopsguru"
	
    
		"github.com/aws/aws-sdk-go-v2/service/directconnect"
	
    
		"github.com/aws/aws-sdk-go-v2/service/directoryservice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/dlm"
	
    
		"github.com/aws/aws-sdk-go-v2/service/docdb"
	
    
		"github.com/aws/aws-sdk-go-v2/service/docdbelastic"
	
    
		"github.com/aws/aws-sdk-go-v2/service/drs"
	
    
		"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	
    
		"github.com/aws/aws-sdk-go-v2/service/dynamodbstreams"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ebs"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ec2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ec2instanceconnect"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ecr"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ecrpublic"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ecs"
	
    
		"github.com/aws/aws-sdk-go-v2/service/efs"
	
    
		"github.com/aws/aws-sdk-go-v2/service/eks"
	
    
		"github.com/aws/aws-sdk-go-v2/service/elasticache"
	
    
		"github.com/aws/aws-sdk-go-v2/service/elasticbeanstalk"
	
    
		"github.com/aws/aws-sdk-go-v2/service/elasticinference"
	
    
		"github.com/aws/aws-sdk-go-v2/service/elasticloadbalancing"
	
    
		"github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/elasticsearchservice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/elastictranscoder"
	
    
		"github.com/aws/aws-sdk-go-v2/service/emr"
	
    
		"github.com/aws/aws-sdk-go-v2/service/emrcontainers"
	
    
		"github.com/aws/aws-sdk-go-v2/service/emrserverless"
	
    
		"github.com/aws/aws-sdk-go-v2/service/eventbridge"
	
    
		"github.com/aws/aws-sdk-go-v2/service/evidently"
	
    
		"github.com/aws/aws-sdk-go-v2/service/finspace"
	
    
		"github.com/aws/aws-sdk-go-v2/service/finspacedata"
	
    
		"github.com/aws/aws-sdk-go-v2/service/firehose"
	
    
		"github.com/aws/aws-sdk-go-v2/service/fis"
	
    
		"github.com/aws/aws-sdk-go-v2/service/fms"
	
    
		"github.com/aws/aws-sdk-go-v2/service/forecast"
	
    
		"github.com/aws/aws-sdk-go-v2/service/forecastquery"
	
    
		"github.com/aws/aws-sdk-go-v2/service/frauddetector"
	
    
		"github.com/aws/aws-sdk-go-v2/service/fsx"
	
    
		"github.com/aws/aws-sdk-go-v2/service/gamelift"
	
    
		"github.com/aws/aws-sdk-go-v2/service/gamesparks"
	
    
		"github.com/aws/aws-sdk-go-v2/service/glacier"
	
    
		"github.com/aws/aws-sdk-go-v2/service/globalaccelerator"
	
    
		"github.com/aws/aws-sdk-go-v2/service/glue"
	
    
		"github.com/aws/aws-sdk-go-v2/service/grafana"
	
    
		"github.com/aws/aws-sdk-go-v2/service/greengrass"
	
    
		"github.com/aws/aws-sdk-go-v2/service/greengrassv2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/groundstation"
	
    
		"github.com/aws/aws-sdk-go-v2/service/guardduty"
	
    
		"github.com/aws/aws-sdk-go-v2/service/health"
	
    
		"github.com/aws/aws-sdk-go-v2/service/healthlake"
	
    
		"github.com/aws/aws-sdk-go-v2/service/honeycode"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iam"
	
    
		"github.com/aws/aws-sdk-go-v2/service/identitystore"
	
    
		"github.com/aws/aws-sdk-go-v2/service/imagebuilder"
	
    
		"github.com/aws/aws-sdk-go-v2/service/inspector"
	
    
		"github.com/aws/aws-sdk-go-v2/service/inspector2"
	
    
    
		"github.com/aws/aws-sdk-go-v2/service/internetmonitor"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iot"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iot1clickdevicesservice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iot1clickprojects"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotanalytics"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotdataplane"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotdeviceadvisor"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotevents"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ioteventsdata"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotfleethub"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotfleetwise"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotjobsdataplane"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotroborunner"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotsecuretunneling"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotsitewise"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotthingsgraph"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iottwinmaker"
	
    
		"github.com/aws/aws-sdk-go-v2/service/iotwireless"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ivs"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ivschat"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ivsrealtime"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kafka"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kafkaconnect"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kendra"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kendraranking"
	
    
		"github.com/aws/aws-sdk-go-v2/service/keyspaces"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kinesis"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kinesisanalytics"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kinesisanalyticsv2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kinesisvideo"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kinesisvideoarchivedmedia"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kinesisvideomedia"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kinesisvideosignaling"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kinesisvideowebrtcstorage"
	
    
		"github.com/aws/aws-sdk-go-v2/service/kms"
	
    
		"github.com/aws/aws-sdk-go-v2/service/lakeformation"
	
    
		"github.com/aws/aws-sdk-go-v2/service/lambda"
	
    
		"github.com/aws/aws-sdk-go-v2/service/lexmodelbuildingservice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/lexmodelsv2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/lexruntimeservice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/lexruntimev2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/licensemanager"
	
    
		"github.com/aws/aws-sdk-go-v2/service/licensemanagerlinuxsubscriptions"
	
    
		"github.com/aws/aws-sdk-go-v2/service/licensemanagerusersubscriptions"
	
    
		"github.com/aws/aws-sdk-go-v2/service/lightsail"
	
    
		"github.com/aws/aws-sdk-go-v2/service/location"
	
    
		"github.com/aws/aws-sdk-go-v2/service/lookoutequipment"
	
    
		"github.com/aws/aws-sdk-go-v2/service/lookoutmetrics"
	
    
		"github.com/aws/aws-sdk-go-v2/service/lookoutvision"
	
    
		"github.com/aws/aws-sdk-go-v2/service/m2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/machinelearning"
	
    
		"github.com/aws/aws-sdk-go-v2/service/macie"
	
    
		"github.com/aws/aws-sdk-go-v2/service/macie2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/managedblockchain"
	
    
		"github.com/aws/aws-sdk-go-v2/service/marketplacecatalog"
	
    
		"github.com/aws/aws-sdk-go-v2/service/marketplacecommerceanalytics"
	
    
		"github.com/aws/aws-sdk-go-v2/service/marketplaceentitlementservice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/marketplacemetering"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mediaconnect"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mediaconvert"
	
    
		"github.com/aws/aws-sdk-go-v2/service/medialive"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mediapackage"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mediapackagev2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mediapackagevod"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mediastore"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mediastoredata"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mediatailor"
	
    
		"github.com/aws/aws-sdk-go-v2/service/medicalimaging"
	
    
		"github.com/aws/aws-sdk-go-v2/service/memorydb"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mgn"
	
    
		"github.com/aws/aws-sdk-go-v2/service/migrationhub"
	
    
		"github.com/aws/aws-sdk-go-v2/service/migrationhubconfig"
	
    
		"github.com/aws/aws-sdk-go-v2/service/migrationhuborchestrator"
	
    
		"github.com/aws/aws-sdk-go-v2/service/migrationhubrefactorspaces"
	
    
		"github.com/aws/aws-sdk-go-v2/service/migrationhubstrategy"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mobile"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mq"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mturk"
	
    
		"github.com/aws/aws-sdk-go-v2/service/mwaa"
	
    
		"github.com/aws/aws-sdk-go-v2/service/neptune"
	
    
		"github.com/aws/aws-sdk-go-v2/service/networkfirewall"
	
    
		"github.com/aws/aws-sdk-go-v2/service/networkmanager"
	
    
		"github.com/aws/aws-sdk-go-v2/service/nimble"
	
    
		"github.com/aws/aws-sdk-go-v2/service/oam"
	
    
		"github.com/aws/aws-sdk-go-v2/service/omics"
	
    
		"github.com/aws/aws-sdk-go-v2/service/opensearch"
	
    
		"github.com/aws/aws-sdk-go-v2/service/opensearchserverless"
	
    
		"github.com/aws/aws-sdk-go-v2/service/opsworks"
	
    
		"github.com/aws/aws-sdk-go-v2/service/opsworkscm"
	
    
		"github.com/aws/aws-sdk-go-v2/service/organizations"
	
    
		"github.com/aws/aws-sdk-go-v2/service/osis"
	
    
		"github.com/aws/aws-sdk-go-v2/service/outposts"
	
    
		"github.com/aws/aws-sdk-go-v2/service/panorama"
	
    
		"github.com/aws/aws-sdk-go-v2/service/paymentcryptography"
	
    
		"github.com/aws/aws-sdk-go-v2/service/paymentcryptographydata"
	
    
		"github.com/aws/aws-sdk-go-v2/service/personalize"
	
    
		"github.com/aws/aws-sdk-go-v2/service/personalizeevents"
	
    
		"github.com/aws/aws-sdk-go-v2/service/personalizeruntime"
	
    
		"github.com/aws/aws-sdk-go-v2/service/pi"
	
    
		"github.com/aws/aws-sdk-go-v2/service/pinpoint"
	
    
		"github.com/aws/aws-sdk-go-v2/service/pinpointemail"
	
    
		"github.com/aws/aws-sdk-go-v2/service/pinpointsmsvoice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/pinpointsmsvoicev2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/pipes"
	
    
		"github.com/aws/aws-sdk-go-v2/service/polly"
	
    
		"github.com/aws/aws-sdk-go-v2/service/pricing"
	
    
		"github.com/aws/aws-sdk-go-v2/service/privatenetworks"
	
    
		"github.com/aws/aws-sdk-go-v2/service/proton"
	
    
		"github.com/aws/aws-sdk-go-v2/service/qldb"
	
    
		"github.com/aws/aws-sdk-go-v2/service/qldbsession"
	
    
		"github.com/aws/aws-sdk-go-v2/service/quicksight"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ram"
	
    
		"github.com/aws/aws-sdk-go-v2/service/rbin"
	
    
		"github.com/aws/aws-sdk-go-v2/service/rds"
	
    
		"github.com/aws/aws-sdk-go-v2/service/rdsdata"
	
    
		"github.com/aws/aws-sdk-go-v2/service/redshift"
	
    
		"github.com/aws/aws-sdk-go-v2/service/redshiftdata"
	
    
		"github.com/aws/aws-sdk-go-v2/service/redshiftserverless"
	
    
		"github.com/aws/aws-sdk-go-v2/service/rekognition"
	
    
		"github.com/aws/aws-sdk-go-v2/service/resiliencehub"
	
    
		"github.com/aws/aws-sdk-go-v2/service/resourceexplorer2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/resourcegroups"
	
    
		"github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi"
	
    
		"github.com/aws/aws-sdk-go-v2/service/robomaker"
	
    
		"github.com/aws/aws-sdk-go-v2/service/rolesanywhere"
	
    
		"github.com/aws/aws-sdk-go-v2/service/route53"
	
    
		"github.com/aws/aws-sdk-go-v2/service/route53domains"
	
    
		"github.com/aws/aws-sdk-go-v2/service/route53recoverycluster"
	
    
		"github.com/aws/aws-sdk-go-v2/service/route53recoverycontrolconfig"
	
    
		"github.com/aws/aws-sdk-go-v2/service/route53recoveryreadiness"
	
    
		"github.com/aws/aws-sdk-go-v2/service/route53resolver"
	
    
		"github.com/aws/aws-sdk-go-v2/service/rum"
	
    
		"github.com/aws/aws-sdk-go-v2/service/s3"
	
    
		"github.com/aws/aws-sdk-go-v2/service/s3control"
	
    
		"github.com/aws/aws-sdk-go-v2/service/s3outposts"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sagemaker"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sagemakera2iruntime"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sagemakeredge"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sagemakerfeaturestoreruntime"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sagemakergeospatial"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sagemakermetrics"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sagemakerruntime"
	
    
		"github.com/aws/aws-sdk-go-v2/service/savingsplans"
	
    
		"github.com/aws/aws-sdk-go-v2/service/scheduler"
	
    
		"github.com/aws/aws-sdk-go-v2/service/schemas"
	
    
		"github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	
    
		"github.com/aws/aws-sdk-go-v2/service/securityhub"
	
    
		"github.com/aws/aws-sdk-go-v2/service/securitylake"
	
    
		"github.com/aws/aws-sdk-go-v2/service/serverlessapplicationrepository"
	
    
		"github.com/aws/aws-sdk-go-v2/service/servicecatalog"
	
    
		"github.com/aws/aws-sdk-go-v2/service/servicecatalogappregistry"
	
    
		"github.com/aws/aws-sdk-go-v2/service/servicediscovery"
	
    
		"github.com/aws/aws-sdk-go-v2/service/servicequotas"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ses"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sesv2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sfn"
	
    
		"github.com/aws/aws-sdk-go-v2/service/shield"
	
    
		"github.com/aws/aws-sdk-go-v2/service/signer"
	
    
		"github.com/aws/aws-sdk-go-v2/service/simspaceweaver"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sms"
	
    
		"github.com/aws/aws-sdk-go-v2/service/snowball"
	
    
		"github.com/aws/aws-sdk-go-v2/service/snowdevicemanagement"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sns"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sqs"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ssm"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ssmcontacts"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ssmincidents"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ssmsap"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sso"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ssoadmin"
	
    
		"github.com/aws/aws-sdk-go-v2/service/ssooidc"
	
    
		"github.com/aws/aws-sdk-go-v2/service/storagegateway"
	
    
		"github.com/aws/aws-sdk-go-v2/service/sts"
	
    
		"github.com/aws/aws-sdk-go-v2/service/support"
	
    
		"github.com/aws/aws-sdk-go-v2/service/supportapp"
	
    
		"github.com/aws/aws-sdk-go-v2/service/swf"
	
    
		"github.com/aws/aws-sdk-go-v2/service/synthetics"
	
    
		"github.com/aws/aws-sdk-go-v2/service/textract"
	
    
		"github.com/aws/aws-sdk-go-v2/service/timestreamquery"
	
    
		"github.com/aws/aws-sdk-go-v2/service/timestreamwrite"
	
    
		"github.com/aws/aws-sdk-go-v2/service/tnb"
	
    
		"github.com/aws/aws-sdk-go-v2/service/transcribe"
	
    
		"github.com/aws/aws-sdk-go-v2/service/transcribestreaming"
	
    
		"github.com/aws/aws-sdk-go-v2/service/transfer"
	
    
		"github.com/aws/aws-sdk-go-v2/service/translate"
	
    
		"github.com/aws/aws-sdk-go-v2/service/verifiedpermissions"
	
    
		"github.com/aws/aws-sdk-go-v2/service/voiceid"
	
    
		"github.com/aws/aws-sdk-go-v2/service/vpclattice"
	
    
		"github.com/aws/aws-sdk-go-v2/service/waf"
	
    
		"github.com/aws/aws-sdk-go-v2/service/wafregional"
	
    
		"github.com/aws/aws-sdk-go-v2/service/wafv2"
	
    
		"github.com/aws/aws-sdk-go-v2/service/wellarchitected"
	
    
		"github.com/aws/aws-sdk-go-v2/service/wisdom"
	
    
		"github.com/aws/aws-sdk-go-v2/service/workdocs"
	
    
		"github.com/aws/aws-sdk-go-v2/service/worklink"
	
    
		"github.com/aws/aws-sdk-go-v2/service/workmail"
	
    
		"github.com/aws/aws-sdk-go-v2/service/workmailmessageflow"
	
    
		"github.com/aws/aws-sdk-go-v2/service/workspaces"
	
    
		"github.com/aws/aws-sdk-go-v2/service/workspacesweb"
	
    
		"github.com/aws/aws-sdk-go-v2/service/xray"
	
)

func initClients () []interface{} {
	clients := []interface{}{}
    
		clients = append(clients,accessanalyzer.Client{})
	
    
		clients = append(clients,account.Client{})
	
    
		clients = append(clients,acm.Client{})
	
    
		clients = append(clients,acmpca.Client{})
	
    
		clients = append(clients,alexaforbusiness.Client{})
	
    
		clients = append(clients,amp.Client{})
	
    
		clients = append(clients,amplify.Client{})
	
    
		clients = append(clients,amplifybackend.Client{})
	
    
		clients = append(clients,amplifyuibuilder.Client{})
	
    
		clients = append(clients,apigateway.Client{})
	
    
		clients = append(clients,apigatewaymanagementapi.Client{})
	
    
		clients = append(clients,apigatewayv2.Client{})
	
    
		clients = append(clients,appconfig.Client{})
	
    
		clients = append(clients,appconfigdata.Client{})
	
    
		clients = append(clients,appfabric.Client{})
	
    
		clients = append(clients,appflow.Client{})
	
    
		clients = append(clients,appintegrations.Client{})
	
    
		clients = append(clients,applicationautoscaling.Client{})
	
    
		clients = append(clients,applicationcostprofiler.Client{})
	
    
		clients = append(clients,applicationdiscoveryservice.Client{})
	
    
		clients = append(clients,applicationinsights.Client{})
	
    
		clients = append(clients,appmesh.Client{})
	
    
		clients = append(clients,apprunner.Client{})
	
    
		clients = append(clients,appstream.Client{})
	
    
		clients = append(clients,appsync.Client{})
	
    
		clients = append(clients,arczonalshift.Client{})
	
    
		clients = append(clients,athena.Client{})
	
    
		clients = append(clients,auditmanager.Client{})
	
    
		clients = append(clients,autoscaling.Client{})
	
    
		clients = append(clients,autoscalingplans.Client{})
	
    
		clients = append(clients,backup.Client{})
	
    
		clients = append(clients,backupgateway.Client{})
	
    
		clients = append(clients,backupstorage.Client{})
	
    
		clients = append(clients,batch.Client{})
	
    
		clients = append(clients,billingconductor.Client{})
	
    
		clients = append(clients,braket.Client{})
	
    
		clients = append(clients,budgets.Client{})
	
    
		clients = append(clients,chime.Client{})
	
    
		clients = append(clients,chimesdkidentity.Client{})
	
    
		clients = append(clients,chimesdkmediapipelines.Client{})
	
    
		clients = append(clients,chimesdkmeetings.Client{})
	
    
		clients = append(clients,chimesdkmessaging.Client{})
	
    
		clients = append(clients,chimesdkvoice.Client{})
	
    
		clients = append(clients,cleanrooms.Client{})
	
    
		clients = append(clients,cloud9.Client{})
	
    
		clients = append(clients,cloudcontrol.Client{})
	
    
		clients = append(clients,clouddirectory.Client{})
	
    
		clients = append(clients,cloudformation.Client{})
	
    
		clients = append(clients,cloudfront.Client{})
	
    
		clients = append(clients,cloudhsm.Client{})
	
    
		clients = append(clients,cloudhsmv2.Client{})
	
    
		clients = append(clients,cloudsearch.Client{})
	
    
		clients = append(clients,cloudsearchdomain.Client{})
	
    
		clients = append(clients,cloudtrail.Client{})
	
    
		clients = append(clients,cloudtraildata.Client{})
	
    
		clients = append(clients,cloudwatch.Client{})
	
    
		clients = append(clients,cloudwatchevents.Client{})
	
    
		clients = append(clients,cloudwatchlogs.Client{})
	
    
		clients = append(clients,codeartifact.Client{})
	
    
		clients = append(clients,codebuild.Client{})
	
    
		clients = append(clients,codecatalyst.Client{})
	
    
		clients = append(clients,codecommit.Client{})
	
    
		clients = append(clients,codedeploy.Client{})
	
    
		clients = append(clients,codeguruprofiler.Client{})
	
    
		clients = append(clients,codegurureviewer.Client{})
	
    
		clients = append(clients,codegurusecurity.Client{})
	
    
		clients = append(clients,codepipeline.Client{})
	
    
		clients = append(clients,codestar.Client{})
	
    
		clients = append(clients,codestarconnections.Client{})
	
    
		clients = append(clients,codestarnotifications.Client{})
	
    
		clients = append(clients,cognitoidentity.Client{})
	
    
		clients = append(clients,cognitoidentityprovider.Client{})
	
    
		clients = append(clients,cognitosync.Client{})
	
    
		clients = append(clients,comprehend.Client{})
	
    
		clients = append(clients,comprehendmedical.Client{})
	
    
		clients = append(clients,computeoptimizer.Client{})
	
    
		clients = append(clients,configservice.Client{})
	
    
		clients = append(clients,connect.Client{})
	
    
		clients = append(clients,connectcampaigns.Client{})
	
    
		clients = append(clients,connectcases.Client{})
	
    
		clients = append(clients,connectcontactlens.Client{})
	
    
		clients = append(clients,connectparticipant.Client{})
	
    
		clients = append(clients,controltower.Client{})
	
    
		clients = append(clients,costandusagereportservice.Client{})
	
    
		clients = append(clients,costexplorer.Client{})
	
    
		clients = append(clients,customerprofiles.Client{})
	
    
		clients = append(clients,databasemigrationservice.Client{})
	
    
		clients = append(clients,databrew.Client{})
	
    
		clients = append(clients,dataexchange.Client{})
	
    
		clients = append(clients,datapipeline.Client{})
	
    
		clients = append(clients,datasync.Client{})
	
    
		clients = append(clients,dax.Client{})
	
    
		clients = append(clients,detective.Client{})
	
    
		clients = append(clients,devicefarm.Client{})
	
    
		clients = append(clients,devopsguru.Client{})
	
    
		clients = append(clients,directconnect.Client{})
	
    
		clients = append(clients,directoryservice.Client{})
	
    
		clients = append(clients,dlm.Client{})
	
    
		clients = append(clients,docdb.Client{})
	
    
		clients = append(clients,docdbelastic.Client{})
	
    
		clients = append(clients,drs.Client{})
	
    
		clients = append(clients,dynamodb.Client{})
	
    
		clients = append(clients,dynamodbstreams.Client{})
	
    
		clients = append(clients,ebs.Client{})
	
    
		clients = append(clients,ec2.Client{})
	
    
		clients = append(clients,ec2instanceconnect.Client{})
	
    
		clients = append(clients,ecr.Client{})
	
    
		clients = append(clients,ecrpublic.Client{})
	
    
		clients = append(clients,ecs.Client{})
	
    
		clients = append(clients,efs.Client{})
	
    
		clients = append(clients,eks.Client{})
	
    
		clients = append(clients,elasticache.Client{})
	
    
		clients = append(clients,elasticbeanstalk.Client{})
	
    
		clients = append(clients,elasticinference.Client{})
	
    
		clients = append(clients,elasticloadbalancing.Client{})
	
    
		clients = append(clients,elasticloadbalancingv2.Client{})
	
    
		clients = append(clients,elasticsearchservice.Client{})
	
    
		clients = append(clients,elastictranscoder.Client{})
	
    
		clients = append(clients,emr.Client{})
	
    
		clients = append(clients,emrcontainers.Client{})
	
    
		clients = append(clients,emrserverless.Client{})
	
    
		clients = append(clients,eventbridge.Client{})
	
    
		clients = append(clients,evidently.Client{})
	
    
		clients = append(clients,finspace.Client{})
	
    
		clients = append(clients,finspacedata.Client{})
	
    
		clients = append(clients,firehose.Client{})
	
    
		clients = append(clients,fis.Client{})
	
    
		clients = append(clients,fms.Client{})
	
    
		clients = append(clients,forecast.Client{})
	
    
		clients = append(clients,forecastquery.Client{})
	
    
		clients = append(clients,frauddetector.Client{})
	
    
		clients = append(clients,fsx.Client{})
	
    
		clients = append(clients,gamelift.Client{})
	
    
		clients = append(clients,gamesparks.Client{})
	
    
		clients = append(clients,glacier.Client{})
	
    
		clients = append(clients,globalaccelerator.Client{})
	
    
		clients = append(clients,glue.Client{})
	
    
		clients = append(clients,grafana.Client{})
	
    
		clients = append(clients,greengrass.Client{})
	
    
		clients = append(clients,greengrassv2.Client{})
	
    
		clients = append(clients,groundstation.Client{})
	
    
		clients = append(clients,guardduty.Client{})
	
    
		clients = append(clients,health.Client{})
	
    
		clients = append(clients,healthlake.Client{})
	
    
		clients = append(clients,honeycode.Client{})
	
    
		clients = append(clients,iam.Client{})
	
    
		clients = append(clients,identitystore.Client{})
	
    
		clients = append(clients,imagebuilder.Client{})
	
    
		clients = append(clients,inspector.Client{})
	
    
		clients = append(clients,inspector2.Client{})
	
    
    
		clients = append(clients,internetmonitor.Client{})
	
    
		clients = append(clients,iot.Client{})
	
    
		clients = append(clients,iot1clickdevicesservice.Client{})
	
    
		clients = append(clients,iot1clickprojects.Client{})
	
    
		clients = append(clients,iotanalytics.Client{})
	
    
		clients = append(clients,iotdataplane.Client{})
	
    
		clients = append(clients,iotdeviceadvisor.Client{})
	
    
		clients = append(clients,iotevents.Client{})
	
    
		clients = append(clients,ioteventsdata.Client{})
	
    
		clients = append(clients,iotfleethub.Client{})
	
    
		clients = append(clients,iotfleetwise.Client{})
	
    
		clients = append(clients,iotjobsdataplane.Client{})
	
    
		clients = append(clients,iotroborunner.Client{})
	
    
		clients = append(clients,iotsecuretunneling.Client{})
	
    
		clients = append(clients,iotsitewise.Client{})
	
    
		clients = append(clients,iotthingsgraph.Client{})
	
    
		clients = append(clients,iottwinmaker.Client{})
	
    
		clients = append(clients,iotwireless.Client{})
	
    
		clients = append(clients,ivs.Client{})
	
    
		clients = append(clients,ivschat.Client{})
	
    
		clients = append(clients,ivsrealtime.Client{})
	
    
		clients = append(clients,kafka.Client{})
	
    
		clients = append(clients,kafkaconnect.Client{})
	
    
		clients = append(clients,kendra.Client{})
	
    
		clients = append(clients,kendraranking.Client{})
	
    
		clients = append(clients,keyspaces.Client{})
	
    
		clients = append(clients,kinesis.Client{})
	
    
		clients = append(clients,kinesisanalytics.Client{})
	
    
		clients = append(clients,kinesisanalyticsv2.Client{})
	
    
		clients = append(clients,kinesisvideo.Client{})
	
    
		clients = append(clients,kinesisvideoarchivedmedia.Client{})
	
    
		clients = append(clients,kinesisvideomedia.Client{})
	
    
		clients = append(clients,kinesisvideosignaling.Client{})
	
    
		clients = append(clients,kinesisvideowebrtcstorage.Client{})
	
    
		clients = append(clients,kms.Client{})
	
    
		clients = append(clients,lakeformation.Client{})
	
    
		clients = append(clients,lambda.Client{})
	
    
		clients = append(clients,lexmodelbuildingservice.Client{})
	
    
		clients = append(clients,lexmodelsv2.Client{})
	
    
		clients = append(clients,lexruntimeservice.Client{})
	
    
		clients = append(clients,lexruntimev2.Client{})
	
    
		clients = append(clients,licensemanager.Client{})
	
    
		clients = append(clients,licensemanagerlinuxsubscriptions.Client{})
	
    
		clients = append(clients,licensemanagerusersubscriptions.Client{})
	
    
		clients = append(clients,lightsail.Client{})
	
    
		clients = append(clients,location.Client{})
	
    
		clients = append(clients,lookoutequipment.Client{})
	
    
		clients = append(clients,lookoutmetrics.Client{})
	
    
		clients = append(clients,lookoutvision.Client{})
	
    
		clients = append(clients,m2.Client{})
	
    
		clients = append(clients,machinelearning.Client{})
	
    
		clients = append(clients,macie.Client{})
	
    
		clients = append(clients,macie2.Client{})
	
    
		clients = append(clients,managedblockchain.Client{})
	
    
		clients = append(clients,marketplacecatalog.Client{})
	
    
		clients = append(clients,marketplacecommerceanalytics.Client{})
	
    
		clients = append(clients,marketplaceentitlementservice.Client{})
	
    
		clients = append(clients,marketplacemetering.Client{})
	
    
		clients = append(clients,mediaconnect.Client{})
	
    
		clients = append(clients,mediaconvert.Client{})
	
    
		clients = append(clients,medialive.Client{})
	
    
		clients = append(clients,mediapackage.Client{})
	
    
		clients = append(clients,mediapackagev2.Client{})
	
    
		clients = append(clients,mediapackagevod.Client{})
	
    
		clients = append(clients,mediastore.Client{})
	
    
		clients = append(clients,mediastoredata.Client{})
	
    
		clients = append(clients,mediatailor.Client{})
	
    
		clients = append(clients,medicalimaging.Client{})
	
    
		clients = append(clients,memorydb.Client{})
	
    
		clients = append(clients,mgn.Client{})
	
    
		clients = append(clients,migrationhub.Client{})
	
    
		clients = append(clients,migrationhubconfig.Client{})
	
    
		clients = append(clients,migrationhuborchestrator.Client{})
	
    
		clients = append(clients,migrationhubrefactorspaces.Client{})
	
    
		clients = append(clients,migrationhubstrategy.Client{})
	
    
		clients = append(clients,mobile.Client{})
	
    
		clients = append(clients,mq.Client{})
	
    
		clients = append(clients,mturk.Client{})
	
    
		clients = append(clients,mwaa.Client{})
	
    
		clients = append(clients,neptune.Client{})
	
    
		clients = append(clients,networkfirewall.Client{})
	
    
		clients = append(clients,networkmanager.Client{})
	
    
		clients = append(clients,nimble.Client{})
	
    
		clients = append(clients,oam.Client{})
	
    
		clients = append(clients,omics.Client{})
	
    
		clients = append(clients,opensearch.Client{})
	
    
		clients = append(clients,opensearchserverless.Client{})
	
    
		clients = append(clients,opsworks.Client{})
	
    
		clients = append(clients,opsworkscm.Client{})
	
    
		clients = append(clients,organizations.Client{})
	
    
		clients = append(clients,osis.Client{})
	
    
		clients = append(clients,outposts.Client{})
	
    
		clients = append(clients,panorama.Client{})
	
    
		clients = append(clients,paymentcryptography.Client{})
	
    
		clients = append(clients,paymentcryptographydata.Client{})
	
    
		clients = append(clients,personalize.Client{})
	
    
		clients = append(clients,personalizeevents.Client{})
	
    
		clients = append(clients,personalizeruntime.Client{})
	
    
		clients = append(clients,pi.Client{})
	
    
		clients = append(clients,pinpoint.Client{})
	
    
		clients = append(clients,pinpointemail.Client{})
	
    
		clients = append(clients,pinpointsmsvoice.Client{})
	
    
		clients = append(clients,pinpointsmsvoicev2.Client{})
	
    
		clients = append(clients,pipes.Client{})
	
    
		clients = append(clients,polly.Client{})
	
    
		clients = append(clients,pricing.Client{})
	
    
		clients = append(clients,privatenetworks.Client{})
	
    
		clients = append(clients,proton.Client{})
	
    
		clients = append(clients,qldb.Client{})
	
    
		clients = append(clients,qldbsession.Client{})
	
    
		clients = append(clients,quicksight.Client{})
	
    
		clients = append(clients,ram.Client{})
	
    
		clients = append(clients,rbin.Client{})
	
    
		clients = append(clients,rds.Client{})
	
    
		clients = append(clients,rdsdata.Client{})
	
    
		clients = append(clients,redshift.Client{})
	
    
		clients = append(clients,redshiftdata.Client{})
	
    
		clients = append(clients,redshiftserverless.Client{})
	
    
		clients = append(clients,rekognition.Client{})
	
    
		clients = append(clients,resiliencehub.Client{})
	
    
		clients = append(clients,resourceexplorer2.Client{})
	
    
		clients = append(clients,resourcegroups.Client{})
	
    
		clients = append(clients,resourcegroupstaggingapi.Client{})
	
    
		clients = append(clients,robomaker.Client{})
	
    
		clients = append(clients,rolesanywhere.Client{})
	
    
		clients = append(clients,route53.Client{})
	
    
		clients = append(clients,route53domains.Client{})
	
    
		clients = append(clients,route53recoverycluster.Client{})
	
    
		clients = append(clients,route53recoverycontrolconfig.Client{})
	
    
		clients = append(clients,route53recoveryreadiness.Client{})
	
    
		clients = append(clients,route53resolver.Client{})
	
    
		clients = append(clients,rum.Client{})
	
    
		clients = append(clients,s3.Client{})
	
    
		clients = append(clients,s3control.Client{})
	
    
		clients = append(clients,s3outposts.Client{})
	
    
		clients = append(clients,sagemaker.Client{})
	
    
		clients = append(clients,sagemakera2iruntime.Client{})
	
    
		clients = append(clients,sagemakeredge.Client{})
	
    
		clients = append(clients,sagemakerfeaturestoreruntime.Client{})
	
    
		clients = append(clients,sagemakergeospatial.Client{})
	
    
		clients = append(clients,sagemakermetrics.Client{})
	
    
		clients = append(clients,sagemakerruntime.Client{})
	
    
		clients = append(clients,savingsplans.Client{})
	
    
		clients = append(clients,scheduler.Client{})
	
    
		clients = append(clients,schemas.Client{})
	
    
		clients = append(clients,secretsmanager.Client{})
	
    
		clients = append(clients,securityhub.Client{})
	
    
		clients = append(clients,securitylake.Client{})
	
    
		clients = append(clients,serverlessapplicationrepository.Client{})
	
    
		clients = append(clients,servicecatalog.Client{})
	
    
		clients = append(clients,servicecatalogappregistry.Client{})
	
    
		clients = append(clients,servicediscovery.Client{})
	
    
		clients = append(clients,servicequotas.Client{})
	
    
		clients = append(clients,ses.Client{})
	
    
		clients = append(clients,sesv2.Client{})
	
    
		clients = append(clients,sfn.Client{})
	
    
		clients = append(clients,shield.Client{})
	
    
		clients = append(clients,signer.Client{})
	
    
		clients = append(clients,simspaceweaver.Client{})
	
    
		clients = append(clients,sms.Client{})
	
    
		clients = append(clients,snowball.Client{})
	
    
		clients = append(clients,snowdevicemanagement.Client{})
	
    
		clients = append(clients,sns.Client{})
	
    
		clients = append(clients,sqs.Client{})
	
    
		clients = append(clients,ssm.Client{})
	
    
		clients = append(clients,ssmcontacts.Client{})
	
    
		clients = append(clients,ssmincidents.Client{})
	
    
		clients = append(clients,ssmsap.Client{})
	
    
		clients = append(clients,sso.Client{})
	
    
		clients = append(clients,ssoadmin.Client{})
	
    
		clients = append(clients,ssooidc.Client{})
	
    
		clients = append(clients,storagegateway.Client{})
	
    
		clients = append(clients,sts.Client{})
	
    
		clients = append(clients,support.Client{})
	
    
		clients = append(clients,supportapp.Client{})
	
    
		clients = append(clients,swf.Client{})
	
    
		clients = append(clients,synthetics.Client{})
	
    
		clients = append(clients,textract.Client{})
	
    
		clients = append(clients,timestreamquery.Client{})
	
    
		clients = append(clients,timestreamwrite.Client{})
	
    
		clients = append(clients,tnb.Client{})
	
    
		clients = append(clients,transcribe.Client{})
	
    
		clients = append(clients,transcribestreaming.Client{})
	
    
		clients = append(clients,transfer.Client{})
	
    
		clients = append(clients,translate.Client{})
	
    
		clients = append(clients,verifiedpermissions.Client{})
	
    
		clients = append(clients,voiceid.Client{})
	
    
		clients = append(clients,vpclattice.Client{})
	
    
		clients = append(clients,waf.Client{})
	
    
		clients = append(clients,wafregional.Client{})
	
    
		clients = append(clients,wafv2.Client{})
	
    
		clients = append(clients,wellarchitected.Client{})
	
    
		clients = append(clients,wisdom.Client{})
	
    
		clients = append(clients,workdocs.Client{})
	
    
		clients = append(clients,worklink.Client{})
	
    
		clients = append(clients,workmail.Client{})
	
    
		clients = append(clients,workmailmessageflow.Client{})
	
    
		clients = append(clients,workspaces.Client{})
	
    
		clients = append(clients,workspacesweb.Client{})
	
    
		clients = append(clients,xray.Client{})
		
	return clients
}
