name: Update Services
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make gen
      - run: git status
