name: Update Services
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make gen
      - run: |
          if git status | grep "modified:   cmd/services.go"
          then
            git config --global user.name 'Simon Davis'
            git config --global user.email 'simon@breathingdust.com'
            git commit -am "Automated services update"
            git push          
          fi
